<a href="https://colab.research.google.com/github/swarna2/numpyPractice/blob/main/numpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
one_dimensional_array=np.array([1,2,3,4,5])
two_dimensional_array=np.array([[1,2],[2,3]])
sequence_of_integer=np.arange(5,12)
random_integers_between_50_and_100=np.random.randint(low=50,high=101,size=6)
random_floats_between_0_and_1=np.random.random([6])
random_floats_between_2_and_3=random_floats_between_0_and_1+2.0
print(one_dimensional_array)
print(two_dimensional_array)
print(sequence_of_integer)
print(random_integers_between_50_and_100)
print(random_floats_between_0_and_1)
print(random_floats_between_2_and_3)

[1 2 3 4 5]
[[1 2]
 [2 3]]
[ 5  6  7  8  9 10 11]
[51 69 67 57 78 77]
[0.59840672 0.26875732 0.44867923 0.22589907 0.19974373 0.41795511]
[2.59840672 2.26875732 2.44867923 2.22589907 2.19974373 2.41795511]
